# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-26 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentprofile',
            fields=[
                ('studentid', models.AutoField(primary_key=True, serialize=False)),
                ('studentname', models.CharField(max_length=200)),
                ('studentrollno', models.IntegerField(default=0)),
                ('studentcontactno', models.IntegerField(default=0)),
                ('studentpic', models.ImageField(upload_to='')),
                ('studentclass', models.IntegerField(default=0)),
                ('studentquote', models.CharField(max_length=30)),
                ('studentachievements', models.TextField(max_length=3000)),
                ('studentmothername', models.CharField(max_length=200)),
                ('studentfathername', models.CharField(max_length=200)),
                ('studentDescription', models.TextField(max_length=3000)),
                ('studentPreviousYearsPercentage', models.CharField(max_length=30)),
            ],
        ),
    ]
