# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-28 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='teacherprofile',
            fields=[
                ('teacherid', models.AutoField(primary_key=True, serialize=False)),
                ('teachername', models.CharField(max_length=200)),
                ('teachercontactno', models.IntegerField(default=0)),
                ('teacherpic', models.ImageField(upload_to='')),
                ('teacherclass', models.IntegerField(default=0)),
                ('teacherquote', models.CharField(max_length=30)),
                ('teacherqualifications', models.TextField(max_length=3000)),
                ('teacherDescription', models.TextField(max_length=3000)),
            ],
        ),
    ]
