# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-28 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
    ]
