# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-04-29 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210428_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='studentrating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='teacherrating',
            field=models.IntegerField(default=0),
        ),
    ]
