# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-02 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='videolectures',
            fields=[
                ('videoid', models.AutoField(primary_key=True, serialize=False)),
                ('videoname', models.CharField(max_length=200)),
                ('videothumbnail', models.ImageField(upload_to='')),
                ('videoDescription', models.TextField(max_length=3000)),
                ('videoSubject', models.CharField(max_length=200)),
                ('videofile', models.FileField(upload_to=b'')),
            ],
        ),
    ]
