# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-02 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolectures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='videocourses',
            fields=[
                ('courseid', models.AutoField(primary_key=True, serialize=False)),
                ('coursename', models.CharField(max_length=200)),
                ('coursedescription', models.CharField(max_length=200)),
            ],
        ),
    ]
