# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-02 10:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videolectures', '0002_videocourses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocourses',
            name='coursedescription',
            field=models.TextField(max_length=3000),
        ),
    ]
