# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-05-04 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schooldata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolname', models.CharField(max_length=200)),
                ('schoolpassword', models.CharField(max_length=200)),
                ('schoolemail', models.CharField(max_length=200)),
                ('schooldescription', models.TextField(max_length=3000)),
                ('schoolnumber', models.IntegerField(default=0)),
                ('schoolteacherkey', models.CharField(max_length=300)),
                ('schoolstudentkey', models.CharField(max_length=300)),
            ],
        ),
    ]
